const phases=[
['Einführung – Rituale & Gruppengefühl',[
['Hier kommt Lubo aus dem All!','Einführung des Förderprogramms|Gruppenregeln'],['Zusammen sind wir eine Gruppe!','Gruppengefühl stärken|Verstärkerrunde'],['Lubo und die Kinder machen einen Wetterbericht','Stimmungsbarometer|Gefühle erkennen und benennen']]],
['Phase 1 · Was ist passiert? – Aufmerksamkeit & Wahrnehmung',[
['Wir lernen uns besser kennen','Selbst- und Fremdwahrnehmung|Gemeinsamkeiten und Unterschiede'],['Das kann ich gut!','Aufmerksamkeit|Eigene Stärken'],['Auf dem nebligen See','Vertrauen|Auditive Aufmerksamkeit'],['Wer ist alles in der Sternengruppe?','Visuelle Aufmerksamkeit|Gruppengefühl'],['Wir sind die Detektive der Sternengruppe','Aufmerksamkeit|Personen und Situationen wahrnehmen'],['Wir sind eine Gruppe und halten zusammen!','Aufeinander hören|Freundschaften']]],
['Phase 2 · Was fühle ich? – Emotionen verstehen',[
['Mein Körper verrät mir, wie es mir geht!','Körperwahrnehmung|Gefühle und Entspannung'],['Lubo freut sich über seine neuen Freunde','Freude erkennen|Eigene Freudenspender'],['Lubo hat Heimweh','Traurigkeit erkennen|Eigene Ressourcen'],['Lubo hat Ärger bekommen','Ärger und Wut erkennen|Eigene Kompetenzen'],['Lubo hat Angst','Angst erkennen|Eigene Kompetenzen'],['Lubos mutige Freunde','Stärke und Selbstvertrauen|Ressourcen'],['Lubo und die Gefühlsdetektive','Perspektivenübernahme|Situation und Emotion'],['Wie würdest du dich fühlen?','Perspektivenübernahme|Situation und Emotion'],['Eine Busfahrt mit viel Gefühl','Emotionen erkennen und zeigen|Gefühlsansteckung'],['Die Sternengruppe wird gebraucht','Uneindeutige Situationen|Absicht und Versehen'],['Ich fühle mich wohl!','Eigene Ressourcen|Kraftquellen']]],
['Phase 3 · Was kann ich tun? – Emotionsregulation',[
['Lubos Raumschiff ist weg!','Ärgerkontrollstrategie|Gruppenverstärkung'],['Lubo darf nicht mitspielen','Ausgeschlossenheit|Problemlösekreislauf'],['Lubo wird gehänselt','Kränkung|Eigene Kompetenzen'],['Lubo kann ganz ruhig bleiben','Provokationen|Eigene Kompetenzen'],['Zusammen können wir vieles lösen','Verschiedene Gefühle|Eigene Ressourcen']]],
['Phase 4 · Was kann ich tun? – Verhalten in sozialen Situationen',[
['Lubo verliert ein Spiel','Frustration und Wut|Beziehung trotz Wut'],['Lubo lernt, mit Enttäuschungen umzugehen','Enttäuschungen|Soziale Situationen'],['Wir können gut zusammenarbeiten!','Kooperation|Freundschaften'],['Lubo löst einen Streit','Konfliktlösestrategie|Eigene Kompetenzen'],['Sternenfahrt','Handlungsstrategien|Gelerntes vertiefen'],['Lubo möchte gerne mitmachen!','Neue Gruppen|Kompromisse'],['Lubo hat gelernt, wie man gut miteinander umgeht','Gelerntes vertiefen|Freundschaft'],['Lubos neues Raumschiff','Gemeinsames Kunstprojekt|Freundschaft'],['Auf Wiedersehen!','Abschied von Lubo und Gruppe|Ausblick']]]];
let lessons=[],n=1;phases.forEach(p=>p[1].forEach(x=>lessons.push({n:n++,title:x[0],goals:x[1].split('|')})));
const demo={materials:['Handpuppe „Lubo“','Bild von Lubo im Raumschiff','Kleiner Ball','Regelkarten und kleiner Beutel o. Ä.','Lustiges, lebhaftes Lied + Abspielgerät','Schönes Tuch für die Kreismitte'],prep:['Umgang mit der Handpuppe vorher ausprobieren','Raum/Stuhlkreis und Kreismitte vorbereiten','Handpuppe zunächst außerhalb des Raums aufbewahren'],steps:[['Begrüßung & Vorstellung','Lubo als außerirdischen Besucher einführen. Die Kinder erfahren, dass er lernen möchte, wie man auf der Erde gut miteinander umgeht.'],['Namensspiel mit Ball','Ball im Kreis zurollen, Blickkontakt aufnehmen und Namen nennen. In einer zweiten Runde kann der Name des anderen Kindes genannt werden.'],['Gruppenregeln','Gemeinsam wenige verständliche Regeln erarbeiten, bildlich sichtbar machen und positives Verhalten konkret hervorheben.'],['Kooperationsspiel „Eisscholle“','Die Gruppe rückt auf einer kleiner werdenden Fläche zusammen. Schwerpunkt: gemeinsam eine Lösung finden und aufeinander achten.'],['Abschlussritual','Lubo verabschiedet sich; die Gruppe beendet die Stunde mit einem kurzen gemeinsamen Ritual.'] ]};
const key='lubo-demo-v1';let state=JSON.parse(localStorage.getItem(key)||'{}');state.group??='Sternengruppe';state.children??='';state.done??=[];state.notes??={};state.checked??={};const save=()=>localStorage.setItem(key,JSON.stringify(state));
function shell(html){document.querySelector('#app').innerHTML=html}function nav(v){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
function home(){nav('home');shell(`<section class='card hero'><span class='pill'>Muster-App</span><h2>${state.group}</h2><p>Interner Begleiter für Planung, Durchführung und Materialvorbereitung.</p></section><div class='grid'><section class='card'><div class='stat'>${state.done.length}/34</div><b>Stunden durchgeführt</b></section><section class='card'><div class='stat'>${34-state.done.length}</div><b>noch offen</b></section></div><section class='card'><h3>Gruppe</h3><label>Gruppenname</label><input id='group' value='${state.group}'><label>Kinder / Kürzel</label><textarea id='children' rows='4' placeholder='z. B. Mia, Leo, ...'>${state.children}</textarea><div class='actions'><button class='primary' onclick='program()'>Programm öffnen</button><button onclick='lesson(1)'>Stunde 1 als Muster</button></div></section><section class='card note'><b>Hinweis zum Muster</b><p>Alle 34 Stunden sind als Übersicht angelegt. Inhaltlich detailliert ist zunächst Stunde 1. Weitere Stunden können anschließend im gleichen Schema ergänzt werden.</p></section>`);document.querySelector('#group').onchange=e=>{state.group=e.target.value;save()};document.querySelector('#children').onchange=e=>{state.children=e.target.value;save()}}
function program(){nav('program');let idx=0,h=`<section class='card'><h2>Gesamtübersicht · 34 Stunden</h2><p class='muted'>Nach Programmphasen gegliedert. Tippe eine Stunde an, um Ziele und – soweit eingepflegt – den Praxisplan zu öffnen.</p></section>`;phases.forEach(p=>{h+=`<h3 class='phase'>${p[0]}</h3><section class='card'>`;p[1].forEach(()=>{let l=lessons[idx++],d=state.done.includes(l.n);h+=`<div class='lesson ${d?'done':''}'><div class='num'>${l.n}</div><div><b>${l.title}</b><div>${l.goals.map(g=>`<span class='tag'>${g}</span>`).join('')}</div></div><button onclick='lesson(${l.n})'>Öffnen</button></div>`});h+='</section>'});shell(h)}
function lesson(num){nav('program');let l=lessons[num-1],isDemo=num===1;let h=`<button class='back' onclick='program()'>← Übersicht</button><section class='card hero'><span class='pill'>Stunde ${num}</span><h2>${l.title}</h2>${l.goals.map(g=>`<span class='tag'>${g}</span>`).join('')}</section>`;if(!isDemo){h+=`<section class='card note'><h3>Noch nicht ausgearbeitet</h3><p>Diese Stunde ist im Grundgerüst bereits vorhanden. Sobald die entsprechenden Buchseiten vorliegen, ergänzen wir Material, Vorbereitung und einen kompakten eigenen Verlaufsplan.</p></section>`}else{h+=`<section class='card'><h3>Material</h3>${demo.materials.map((m,i)=>check('m'+i,m)).join('')}</section><section class='card'><h3>Vor der Stunde</h3>${demo.prep.map((m,i)=>check('p'+i,m)).join('')}</section><section class='card'><h3>Verlaufsplan</h3>${demo.steps.map(s=>`<div class='step'><b>${s[0]}</b><p>${s[1]}</p></div>`).join('')}</section>`}h+=`<section class='card'><h3>Eigene Notizen</h3><textarea id='note' rows='5' placeholder='Beobachtungen, Anpassungen, Ideen fürs nächste Mal …'>${state.notes[num]||''}</textarea><div class='actions'><button class='primary' onclick='toggleDone(${num})'>${state.done.includes(num)?'✓ Als offen markieren':'✓ Stunde durchgeführt'}</button></div></section>`;shell(h);document.querySelector('#note').onchange=e=>{state.notes[num]=e.target.value;save()}}
function check(id,text){let c=state.checked[id]?'checked':'';return `<label class='check'><input type='checkbox' ${c} onchange='state.checked["${id}"]=this.checked;save()'><span>${text}</span></label>`}
function materials(){nav('materials');shell(`<section class='card'><h2>Materialübersicht</h2><p class='muted'>Im Muster werden die Materialien der bereits detailliert erfassten Stunde 1 zusammengeführt.</p>${demo.materials.map((m,i)=>check('m'+i,m)).join('')}</section><section class='card note'><b>Später möglich:</b><p>Filter „nächste Stunde“, „nächste 5 Stunden“ oder „gesamtes Programm“ sowie eine druckbare Einkauf-/Vorbereitungsliste.</p></section>`)}
function toggleDone(n){let i=state.done.indexOf(n);i>=0?state.done.splice(i,1):state.done.push(n);save();lesson(n)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>({home,program,materials}[b.dataset.view])());document.querySelector('#reset').onclick=()=>{localStorage.removeItem(key);location.reload()};home();
